/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CartridgeOwnable,
  CartridgeOwnableInterface,
} from "../CartridgeOwnable";

const _abi = [
  {
    inputs: [],
    name: "creator",
    outputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CartridgeOwnable__factory {
  static readonly abi = _abi;
  static createInterface(): CartridgeOwnableInterface {
    return new utils.Interface(_abi) as CartridgeOwnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CartridgeOwnable {
    return new Contract(address, _abi, signerOrProvider) as CartridgeOwnable;
  }
}
