/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CatridgeOwnable,
  CatridgeOwnableInterface,
} from "../CatridgeOwnable";

const _abi = [
  {
    inputs: [],
    name: "creator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CatridgeOwnable__factory {
  static readonly abi = _abi;
  static createInterface(): CatridgeOwnableInterface {
    return new utils.Interface(_abi) as CatridgeOwnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CatridgeOwnable {
    return new Contract(address, _abi, signerOrProvider) as CatridgeOwnable;
  }
}
