/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Creatorship, CreatorshipInterface } from "../Creatorship";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "creator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newCreator",
        type: "address",
      },
    ],
    name: "transferCreatorship",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Creatorship__factory {
  static readonly abi = _abi;
  static createInterface(): CreatorshipInterface {
    return new utils.Interface(_abi) as CreatorshipInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Creatorship {
    return new Contract(address, _abi, signerOrProvider) as Creatorship;
  }
}
