/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { HashupIGO, HashupIGOInterface } from "../HashupIGO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_cartridgeAddress",
        type: "address",
      },
    ],
    name: "getCartridgePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cartridgeAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "paymentTokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "setCartridgeForSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610300806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063360067771461003b57806394782b611461006b575b600080fd5b610055600480360381019061005091906101be565b610087565b6040516100629190610245565b60405180910390f35b610085600480360381019061008091906101e7565b6100d2565b005b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101549050919050565b60405180604001604052808373ffffffffffffffffffffffffffffffffffffffff168152602001828152506000808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008201518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555060208201518160010155905050505050565b6000813590506101a38161029c565b92915050565b6000813590506101b8816102b3565b92915050565b6000602082840312156101d057600080fd5b60006101de84828501610194565b91505092915050565b6000806000606084860312156101fc57600080fd5b600061020a86828701610194565b935050602061021b86828701610194565b925050604061022c868287016101a9565b9150509250925092565b61023f81610292565b82525050565b600060208201905061025a6000830184610236565b92915050565b600061026b82610272565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b6102a581610260565b81146102b057600080fd5b50565b6102bc81610292565b81146102c757600080fd5b5056fea2646970667358221220441dd08017af95457750c9f557c37c186c39c8d67e04c2824beaf7a0185f238a64736f6c63430008040033";

export class HashupIGO__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<HashupIGO> {
    return super.deploy(overrides || {}) as Promise<HashupIGO>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): HashupIGO {
    return super.attach(address) as HashupIGO;
  }
  connect(signer: Signer): HashupIGO__factory {
    return super.connect(signer) as HashupIGO__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HashupIGOInterface {
    return new utils.Interface(_abi) as HashupIGOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HashupIGO {
    return new Contract(address, _abi, signerOrProvider) as HashupIGO;
  }
}
