/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HashupIGOInterface extends ethers.utils.Interface {
  functions: {
    "buyCartridge(address,uint256)": FunctionFragment;
    "getCartridgePrice(address)": FunctionFragment;
    "getPaymentToken(address)": FunctionFragment;
    "setCartridgeForSale(address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyCartridge",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCartridgePrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCartridgeForSale",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyCartridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCartridgePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCartridgeForSale",
    data: BytesLike
  ): Result;

  events: {};
}

export class HashupIGO extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HashupIGOInterface;

  functions: {
    buyCartridge(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { price: BigNumber }>;

    getPaymentToken(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<[string] & { paymentToken: string }>;

    setCartridgeForSale(
      _cartridgeAddress: string,
      _paymentTokenAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buyCartridge(
    _cartridgeAddress: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCartridgePrice(
    _cartridgeAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPaymentToken(
    _cartridgeAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  setCartridgeForSale(
    _cartridgeAddress: string,
    _paymentTokenAddress: string,
    _price: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyCartridge(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPaymentToken(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    setCartridgeForSale(
      _cartridgeAddress: string,
      _paymentTokenAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    buyCartridge(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPaymentToken(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setCartridgeForSale(
      _cartridgeAddress: string,
      _paymentTokenAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyCartridge(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPaymentToken(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setCartridgeForSale(
      _cartridgeAddress: string,
      _paymentTokenAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
