/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HashupStoreInterface extends ethers.utils.Interface {
  functions: {
    "burnFee()": FunctionFragment;
    "buyCartridge(address,uint256)": FunctionFragment;
    "creator()": FunctionFragment;
    "distributePayment(uint256)": FunctionFragment;
    "getCartridgePrice(address)": FunctionFragment;
    "hashToken()": FunctionFragment;
    "paymentToken()": FunctionFragment;
    "raisedAmount(address)": FunctionFragment;
    "reflinkAmount(address)": FunctionFragment;
    "reflinkFee()": FunctionFragment;
    "sendCartridgeToStore(address,uint256,uint256)": FunctionFragment;
    "swapRouter()": FunctionFragment;
    "transferCreatorship(address)": FunctionFragment;
    "withdrawCartridges(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "burnFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyCartridge",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "distributePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCartridgePrice",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "hashToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raisedAmount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reflinkAmount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reflinkFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendCartridgeToStore",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferCreatorship",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCartridges",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "burnFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyCartridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCartridgePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hashToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raisedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reflinkAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reflinkFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendCartridgeToStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferCreatorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCartridges",
    data: BytesLike
  ): Result;

  events: {
    "CartridgesBought(address,uint256,uint256)": EventFragment;
    "CartridgesWithdrawn(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SentToStore(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CartridgesBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CartridgesWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SentToStore"): EventFragment;
}

export type CartridgesBoughtEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    cartridgeAddress: string;
    price: BigNumber;
    amount: BigNumber;
  }
>;

export type CartridgesWithdrawnEvent = TypedEvent<
  [string, BigNumber] & { cartridgeAddress: string; amount: BigNumber }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type SentToStoreEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    cartridgeAddress: string;
    price: BigNumber;
    amount: BigNumber;
  }
>;

export class HashupStore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HashupStoreInterface;

  functions: {
    burnFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    "buyCartridge(address,uint256)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "buyCartridge(address,uint256,address)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      _referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    creator(overrides?: CallOverrides): Promise<[string]>;

    distributePayment(
      _totalValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        toCreator: BigNumber;
        toBurn: BigNumber;
        toReferrer: BigNumber;
      }
    >;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { price: BigNumber }>;

    hashToken(overrides?: CallOverrides): Promise<[string]>;

    paymentToken(overrides?: CallOverrides): Promise<[string]>;

    raisedAmount(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    reflinkAmount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    reflinkFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    sendCartridgeToStore(
      _cartridgeAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;

    transferCreatorship(
      _newCreator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawCartridges(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  burnFee(overrides?: CallOverrides): Promise<BigNumber>;

  "buyCartridge(address,uint256)"(
    _cartridgeAddress: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "buyCartridge(address,uint256,address)"(
    _cartridgeAddress: string,
    _amount: BigNumberish,
    _referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  creator(overrides?: CallOverrides): Promise<string>;

  distributePayment(
    _totalValue: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      toCreator: BigNumber;
      toBurn: BigNumber;
      toReferrer: BigNumber;
    }
  >;

  getCartridgePrice(
    _cartridgeAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hashToken(overrides?: CallOverrides): Promise<string>;

  paymentToken(overrides?: CallOverrides): Promise<string>;

  raisedAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  reflinkAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  reflinkFee(overrides?: CallOverrides): Promise<BigNumber>;

  sendCartridgeToStore(
    _cartridgeAddress: string,
    _price: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  transferCreatorship(
    _newCreator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawCartridges(
    _cartridgeAddress: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burnFee(overrides?: CallOverrides): Promise<BigNumber>;

    "buyCartridge(address,uint256)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "buyCartridge(address,uint256,address)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      _referrer: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    creator(overrides?: CallOverrides): Promise<string>;

    distributePayment(
      _totalValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        toCreator: BigNumber;
        toBurn: BigNumber;
        toReferrer: BigNumber;
      }
    >;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashToken(overrides?: CallOverrides): Promise<string>;

    paymentToken(overrides?: CallOverrides): Promise<string>;

    raisedAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    reflinkAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    reflinkFee(overrides?: CallOverrides): Promise<BigNumber>;

    sendCartridgeToStore(
      _cartridgeAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    swapRouter(overrides?: CallOverrides): Promise<string>;

    transferCreatorship(
      _newCreator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawCartridges(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "CartridgesBought(address,uint256,uint256)"(
      cartridgeAddress?: null,
      price?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { cartridgeAddress: string; price: BigNumber; amount: BigNumber }
    >;

    CartridgesBought(
      cartridgeAddress?: null,
      price?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { cartridgeAddress: string; price: BigNumber; amount: BigNumber }
    >;

    "CartridgesWithdrawn(address,uint256)"(
      cartridgeAddress?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { cartridgeAddress: string; amount: BigNumber }
    >;

    CartridgesWithdrawn(
      cartridgeAddress?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { cartridgeAddress: string; amount: BigNumber }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "SentToStore(address,uint256,uint256)"(
      cartridgeAddress?: null,
      price?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { cartridgeAddress: string; price: BigNumber; amount: BigNumber }
    >;

    SentToStore(
      cartridgeAddress?: null,
      price?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { cartridgeAddress: string; price: BigNumber; amount: BigNumber }
    >;
  };

  estimateGas: {
    burnFee(overrides?: CallOverrides): Promise<BigNumber>;

    "buyCartridge(address,uint256)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "buyCartridge(address,uint256,address)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      _referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    creator(overrides?: CallOverrides): Promise<BigNumber>;

    distributePayment(
      _totalValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashToken(overrides?: CallOverrides): Promise<BigNumber>;

    paymentToken(overrides?: CallOverrides): Promise<BigNumber>;

    raisedAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    reflinkAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    reflinkFee(overrides?: CallOverrides): Promise<BigNumber>;

    sendCartridgeToStore(
      _cartridgeAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    transferCreatorship(
      _newCreator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawCartridges(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burnFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "buyCartridge(address,uint256)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "buyCartridge(address,uint256,address)"(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      _referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    creator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    distributePayment(
      _totalValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCartridgePrice(
      _cartridgeAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paymentToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    raisedAmount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reflinkAmount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reflinkFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendCartridgeToStore(
      _cartridgeAddress: string,
      _price: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferCreatorship(
      _newCreator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawCartridges(
      _cartridgeAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
